// Stubs for the DepotDownloader files we exclude from compilation
// (Ansi.cs / AnsiDetector.cs / PlatformUtilities.cs). Those only do console
// cosmetics (ANSI colours, OS taskbar progress, chmod +x) via native P/Invoke
// generated by CsWin32. We don't need any of it — we capture progress from the
// engine's stdout instead — so these harmless no-ops let the engine compile
// without dragging in the CsWin32 source generator. Upstream files stay untouched.

namespace DepotDownloader
{
    static class Ansi
    {
        public enum ProgressState : byte
        {
            Default,
            Indeterminate,
            Error,
            Paused,
            Hidden,
        }

        public static void Init() { }

        public static void Progress(ulong downloaded, ulong total) { }

        public static void Progress(ProgressState state, byte progress = 0) { }
    }

    static class PlatformUtilities
    {
        // On Windows there is no executable bit; no-op is correct.
        public static void SetExecutable(string path, bool value) { }
    }
}
